-- MySQL Script generated by MySQL Workbench
-- Thu Jul  8 11:32:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema provider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema provider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provider` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `provider` ;

-- -----------------------------------------------------
-- Table `provider`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provider`.`service` ;

CREATE TABLE IF NOT EXISTS `provider`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `provider`.`tariff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provider`.`tariff` ;

CREATE TABLE IF NOT EXISTS `provider`.`tariff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price_by_day` DECIMAL(5,2) NOT NULL,
  `title` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `provider`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provider`.`user` ;

CREATE TABLE IF NOT EXISTS `provider`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `account` DECIMAL(6,2) NULL DEFAULT 0.0,
  `status_active` TINYINT(1) NULL DEFAULT 1,
  `status_user` TINYINT(1) NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `provider`.`tariff_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provider`.`tariff_history` ;

CREATE TABLE IF NOT EXISTS `provider`.`tariff_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATE NOT NULL,
  `date_finish` DATE NULL DEFAULT NULL,
  `status` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  `tariff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tariff_history_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_tariff_history_tariff1_idx` (`tariff_id` ASC) VISIBLE,
  CONSTRAINT `fk_tariff_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `provider`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tariff_history_tariff1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `provider`.`tariff` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provider`.`tariff_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provider`.`tariff_service` ;

CREATE TABLE IF NOT EXISTS `provider`.`tariff_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tariff_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tariff_service_tariff1_idx` (`tariff_id` ASC) VISIBLE,
  INDEX `fk_tariff_service_service1_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_tariff_service_tariff1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `provider`.`tariff` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tariff_service_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `provider`.`service` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
