USE provider;
INSERT tariff_service (tariff_id, service_id)
VALUES ( 1, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 2, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 3, 3);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 4, 4);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 5, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 5, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 6, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 6, 3);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 7, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 7, 4);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 8, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 8, 3);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 9, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 9, 4);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 10, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 10, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 10, 3);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 11, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 11, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 11, 4);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 12, 1);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 12, 2);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 12, 3);
INSERT tariff_service (tariff_id, service_id)
VALUES ( 12, 4);